localhost/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path(
        'property/<int:pk>',
        views.PropertyDetailView.as_view(),
        name='property-detail'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile'),
    path(
        'about',
        TemplateView.as_view(template_name='core/about_us.html'),
        name='about'),
]

handler404 = 'core.views.PageNotFoundView'

localhost/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path(
        '',
        views.DashboardView.as_view(),
        name='dashboard'),
    path('listing/add/', views.ListingCreate.as_view(), name='listing-create'),
    path(
        'listing/<int:pk>/delete',
        views.ListingDelete.as_view(),
        name='listing-delete'),
    path(
        'review/listing/<int:pk>',
        views.ListingReviewView.as_view(),
        name='listing-review')
]

localhost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('localhost.core.urls')),
    path('', include('localhost.authentication.urls')),
    path('dashboard/', include('localhost.dashboard.urls')),
    path('messages/', include('localhost.messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

localhost/core/models.py
import json
import logging

from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import IntegrityError, models
from django.db.models import F, Q
from django.db.models.signals import m2m_changed, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_celery_beat.models import (CrontabSchedule, PeriodicTask,
                                       PeriodicTasks)

logger = logging.getLogger(__name__)


class Amenity(models.Model):
    item = models.CharField(max_length=15, unique=True)
    icon = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                regex=r'^fa-[\w]*',
                message=_('Icon class must starts with \"fa-\"'))
        ],
        help_text=_('Font Awesome glyph class.'))

    class Meta:
        verbose_name_plural = 'amenities'

    def __str__(self):
        return f"{self.item}"


class BiddingSession(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()

    @classmethod
    def current_session_of(cls, property_item):
        """
        Helper function to return current session a property item is in.
        """
        now = timezone.localtime().time()
        qs1 = cls.objects.filter(
            Q(start_time__lte=F('end_time')),
            Q(start_time__lte=now),
            end_time__gte=now,
            propertyitem=property_item)
        qs2 = cls.objects.filter(
            Q(start_time__gt=F('end_time')),
            Q(start_time__lte=now)
            | Q(end_time__gte=now),
            propertyitem=property_item)
        return qs1.union(qs2).first()

    def __str__(self):
        return f"""{self.start_time.strftime('%I:%M %p')} - {self.end_time.strftime('%I:%M %p')}"""


class Sin(models.Func):
    function = 'SIN'


class Cos(models.Func):
    function = 'COS'


class Acos(models.Func):
    function = 'ACOS'


class Radians(models.Func):
    function = 'RADIANS'


class DistanceManager(models.Manager):
    """
    Custom manager that adds functions related to geographical distance.
    """

    def within(self, latitude, longitude):
        """
        Returns the distance between two locations given latitude and
        longitude. The distance is calculated using Haversine Formula. See
        https://en.wikipedia.org/wiki/Haversine_formula
        The model that this manager handles must have a latitude and longitutde
        field.

        Usage:
        >>> class Foo(models.Model):
        >>>     latitude = models.DecimalField()
        >>>     longitude = models.DecimalField()
        >>>     objects = DistanceManager()

        >>> Foo.objects.within(lat, lng)
        <QuerySet [<Foo: ...>]>

        Args:
            latitude: Latitude of the given location
            longitude: Longitude of the given location

        Returns:
            A queryset with annotated distance between the given location and
            objects
        """
        radlat = Radians(latitude)  # given latitude
        radlong = Radians(longitude)  # given longitude
        radflat = Radians(models.F('latitude'))
        radflong = Radians(models.F('longitude'))

        # 6371 is for km. Use 3959 for miles
        expr = 6371 * Acos(
            Cos(radlat) * Cos(radflat) * Cos(radflong - radlong) +
            Sin(radlat) * Sin(radflat))

        return self.get_queryset().annotate(distance=expr)


class Property(models.Model):
    host = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(
        _('title'), max_length=100, help_text=_('Character limit: 100'))
    description = models.TextField(
        _('description'), max_length=600, help_text=_('Character limit: 600'))
    address = models.CharField(
        _('address'), max_length=200, help_text=_('Address of this property.'))
    latitude = models.DecimalField(
        max_digits=10, decimal_places=7, editable=False)
    longitude = models.DecimalField(
        max_digits=10, decimal_places=7, editable=False)
    earliest_checkin_time = models.TimeField(
        _('earliest check-in time'),
        help_text=_('Earliest time a guest can check-in.'))
    latest_checkin_time = models.TimeField(
        _('latest check-in time'),
        help_text=_('Latest time a guest can check-in.'))

    objects = DistanceManager()

    class Meta:
        verbose_name_plural = 'properties'

    def get_absolute_url(self):
        return reverse('core:property-detail', args=[str(self.id)])

    def __str__(self):
        return f"Property: {self.title} owned by {self.host} ({self.longitude}, {self.latitude})"


class PropertyItem(models.Model):
    property = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name='property_item')
    title = models.CharField(
        _('title'), max_length=100, help_text=_('Character limit: 100'))
    description = models.TextField(
        _('description'), max_length=600, help_text=_('Character limit: 600'))
    buyout_price = models.PositiveIntegerField(
        _('buyout price'), help_text=_('Buyout price of the auction.'))
    min_price = models.PositiveIntegerField(
        _('min price'), help_text=_('Starting price of the auction.'))
    session = models.ManyToManyField(
        BiddingSession,
        verbose_name=_('bidding session'),
        blank=True,
        help_text=_('Choose a session to enable bidding during those times.'))
    amenities = models.ManyToManyField(
        Amenity, blank=True, help_text=_('Amenities in this place.'))
    capacity = models.PositiveIntegerField()
    available = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('core:property-detail', args=[str(self.property.id)])

    def __str__(self):
        return f"{self.title}"


def property_item_img_path(instance, filename):
    """
    File will be uploaded to
    MEDIA_ROOT/user_<id>/property_item_<property_item_id>/<filename>
    """
    return f"user_{instance.property_item.property.host.id}/property_item_{instance.property_item.id}/{filename}"


def property_img_path(instance, filename):
    """
    File will be uploaded to
    MEDIA_ROOT/user_<id>/property_<property_item_id>/<filename>
    """
    return f"user_{instance.property.host.id}/property_{instance.property.id}/{filename}"


class PropertyImage(models.Model):
    property = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=property_img_path)


class PropertyItemImage(models.Model):
    property_item = models.ForeignKey(
        PropertyItem, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=property_item_img_path)


class Bid(models.Model):
    property_item = models.ForeignKey(
        PropertyItem, on_delete=models.CASCADE, related_name='bids')
    bidder = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()

    class Meta:
        get_latest_by = 'amount'


class Booking(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    property_item = models.ForeignKey(PropertyItem, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(_('price'))
    earliest_checkin_time = models.DateTimeField(_('earliest check-in time'))
    latest_checkin_time = models.DateTimeField(_('latest check-in time'))

    def __str__(self):
        return f"{self.user} booked {self.property_item}"


class PropertyItemReview(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(6)])
    description = models.TextField(_('description'))


class Notification(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    OUTBID = 'O'
    WON_BID = 'W'
    BUYOUT = 'B'
    MESSAGE_CHOICES = ((OUTBID, 'You have been outbid!'),
                       (WON_BID, 'You have won your auction!'),
                       (BUYOUT,
                        'The item you were bidding on was bought out!'))
    message = models.CharField(
        _('message'),
        max_length=1,
        choices=MESSAGE_CHOICES,
    )
    property_item = models.ForeignKey(PropertyItem, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)


@receiver(m2m_changed, sender=PropertyItem.session.through)
def property_item_m2m_changed(instance, action, pk_set, **kwargs):
    """
    Add/remove cleanup task when session has been added to/removed from the
    property item.
    """
    sessions = BiddingSession.objects.filter(id__in=pk_set)
    if action == 'post_add':
        for i, session in enumerate(sessions):
            schedule, _ = CrontabSchedule.objects.get_or_create(
                minute=session.end_time.minute, hour=session.end_time.hour)
            PeriodicTask.objects.get_or_create(
                crontab=schedule,
                task='localhost.core.tasks.cleanup_bids',
                name=f'PropertyItem-{instance.id} bids cleanup {i}',
                args=json.dumps([instance.id]))
    elif action == 'post_remove':
        names = [
            f'PropertyItem-{instance.id} bids cleanup {i}'
            for session in sessions
        ]
        PeriodicTask.objects.filter(name__in=names).delete()


@receiver(pre_save, sender=PropertyItem)
def property_item_pre_save(instance, **kwargs):
    """
    Enable bids every day at 12nn.
    """
    schedule, _ = CrontabSchedule.objects.get_or_create(hour=12, minute=0)
    try:
        PeriodicTask.objects.get_or_create(
            crontab=schedule,
            task='localhost.core.tasks.enable_bids',
            name=f'Daily bids enable {instance.id}',
            args=json.dumps([instance.id]))
    except IntegrityError:

localhost/dashboard/models.py
from django.db import models

# Create your models here.

localhost/dashboard/forms.py
from datetime import datetime, time, timedelta

from django import forms
from django.contrib.auth import get_user_model
from django.forms.models import ModelForm, inlineformset_factory
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from localhost.core.models import Property, PropertyItem, PropertyItemReview
from localhost.core.utils import parse_address

User = get_user_model()


class DatePicker(forms.DateInput):
    input_type = 'date'


class ProfileForm(ModelForm):
    class Meta:
        model = User
        fields = (
            'bio',
            'dob',
            'gender',
        )
        widgets = {
            'bio': forms.Textarea(attrs={
                'cols': 100,
                'rows': 3
            }),
            'dob': DatePicker(),
            'gender': forms.RadioSelect(),
        }


class PropertyItemForm(ModelForm):
    img = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        label='Photos',
        required=False)

    class Meta:
        model = PropertyItem
        fields = '__all__'
        exclude = ('highest_bidder', )


class PropertyForm(ModelForm):
    # TIME_CHOICE in this format [(time object, time in string)]
    TIME_CHOICE = [((datetime.combine(timezone.now(), time()) +
                     timedelta(minutes=i * 30)).time(),
                    (datetime.combine(timezone.now(), time()) +
                     timedelta(minutes=i * 30)).strftime('%H:%M'))
                   for i in range(48)]
    earliest_checkin_time = forms.ChoiceField(
        choices=TIME_CHOICE, help_text=_('Earliest check-in time.'))
    latest_checkin_time = forms.ChoiceField(
        choices=TIME_CHOICE, help_text=_('Latest check-in time.'))
    img = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        label='Photos',
        required=False)

    class Meta:
        model = Property
        exclude = ('host', )

    def clean(self):
        """
        Clean latest_checkin_time and earliest_checkin_time.

        Ensure that earliest_checkin_time < latest_checkin_time.
        """
        cleaned_data = super().clean()
        earliest_checkin_time = cleaned_data.get('earliest_checkin_time')
        latest_checkin_time = cleaned_data.get('latest_checkin_time')
        if (earliest_checkin_time and latest_checkin_time
                and earliest_checkin_time > latest_checkin_time):
            raise forms.ValidationError(
                _('Invalid check-in time: %(earliest)s > %(latest)s'),
                code='invalid-time',
                params={
                    'earliest': earliest_checkin_time,
                    'latest': latest_checkin_time
                })

    def save(self, commit=True):
        new_property = super().save(commit=False)
        new_property.latitude, new_property.longitude = parse_address(
            self.cleaned_data.get('address'))
        if commit:
            new_property.save()
        return new_property


class WalletForm(forms.Form):
    recharge_amount = forms.IntegerField(
        min_value=1, max_value=9223372036854775807)

    class Meta:
        labels = {
            'recharge_amount': 'Add money to wallet',
        }


class PropertyItemReviewForm(ModelForm):
    class Meta:
        model = PropertyItemReview
        fields = (
            'rating',
            'description',
        )
        labels = {
            'description': 'Leave a review...',
        }
        widgets = {
            'rating': forms.HiddenInput(),
        }


PropertyItemFormSet = inlineformset_factory(
    Property, PropertyItem, form=PropertyItemForm, extra=1)

localhost/messaging/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import ListView

from localhost.messaging.models import Message

User = get_user_model()


class MessagingView(LoginRequiredMixin, ListView):
    template_name = 'messaging/messaging.html'
    model = Message

    def get_context_data(self, **kwargs):
        """
        Pass conversations to context.

        context['conversations']: [(user, [messages]), (user, [messages]), ...]
        """
        context = super().get_context_data(**kwargs)
        try:
            recipient = User.objects.get(pk=self.request.GET.get('recipient'))
            context['recipient'] = recipient
        except User.DoesNotExist:
            pass

        auth_user = self.request.user
        messages = self.model.objects.filter(
            Q(sender=auth_user) | Q(recipient=auth_user))
        contacts = User.objects \
            .filter(
                Q(sent_messages__pk__in=messages.values('pk'))
                | Q(received_messages__pk__in=messages.values('pk'))) \
            .exclude(pk=auth_user.pk).distinct()
        conversations = [(user,
                          messages.filter(Q(sender=user) | Q(recipient=user)))
                         for user in contacts]
        context['conversations'] = conversations
        return context

localhost/dashboard/templates/dashboard/active_bids.html
<div class="p-2 flex-grow-1 justify-content-center tab-pane fade show active" id="activity" role="tabpanel">
  {% if active_bids %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Booking</th>
        <th scope="col" class="text-center">Your last bid</th>
        <th scope="col" class="text-center">Current highest bid</th>
      </tr>
    </thead>
    <tbody>
      {% for item in active_bids %}
      <tr>
        <th scope="row">
          <div class="d-flex flex-column m-0">
            <a href="{{ item.get_absolute_url }}" class="m-0"><h5 class="m-0">{{ item.title }}</h5></a>
            <p class="m-0 font-weight-normal">{{ item.property.address }}</p>
          </div>
        </th>
        <td class="align-middle text-center">$<span id="user_bid_item_{{ item.id }}">{{ item.user_bid }}</span></td>
        <td class="align-middle text-center">$<span id="bid_item_{{ item.id }}">{{ item.current_bid }}</span></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="text-primary align-self-center">No recent activity</p>
  {% endif %}
</div>

localhost/dashboard/templates/dashboard/booking_history.html
<div class="p-2 flex-grow-1 justify-content-center tab-pane fade" id="booking-history" role="tabpanel">
  {% if booking_list %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Booking</th>
        <th scope="col">Price</th>
        <th scope="col">Earliest Check-in</th>
        <th scope="col">Latest Check-in Time</th>
        <th scope="col">Leave Review</th>
      </tr>
    </thead>
    <tbody>
      {% for booking in booking_list %}
      <tr>
        <th scope="row">
          <div class="d-flex flex-column m-0">
            <a href="{{ booking.property_item.get_absolute_url }}" class="m-0"><h5 class="m-0">{{ booking.property_item }}</h5></a>
            <p class="m-0 font-weight-normal">{{ booking.property_item.property.address }}</p>
          </div>
        </th>
        <td class="align-middle">${{ booking.price }}</td>
        <td class="align-middle">{{ booking.earliest_checkin_time|date }} {{ booking.earliest_checkin_time|time }}</td>
        <td class="align-middle">{{ booking.latest_checkin_time|time }}</td>
        <td class="align-middle">
          {% if booking.can_cancel %}
          <a href="" class="btn">Cancel Booking</a>
          {% elif booking.reviewed or not booking.passed_one_day %}
          <button class="btn" disabled>Review</button>
          {% else %}
          <a href="{% url 'dashboard:listing-review' booking.id %}" class="btn text-white bg-accent">Review</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="text-primary align-self-center">No previous bookings</p>
  {% endif %}
</div>

localhost/dashboard/templates/dashboard/dashboard_base.html
{% extends "core/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/header.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/footer.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/panel.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/dashboard.css" %}">
{% endblock %}

{% block title %} {{ block.super }} - Dashboard {% endblock %}

{% block main-container %}
<div id="main-flex-wrapper" class="container-fluid d-flex flex-column justify-content-between p-0">
{% endblock %}

{% block body_wrapped %}
<div class="container-fluid d-flex flex-row flex-grow-1 justify-content-center p-0 min-height-0">
  <div id="contacts" class="collapse navbar-collapse">
    <div id="v-pills-tab" class="d-flex flex-column py-3 justify-content-between h-100" role="tablist">
      <div class="d-flex flex-column list-nav nav nav-pills">
        <h2 class="text-center p-1">Dashboard</h2>
        <span class="header-divider"></span>
        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#activity" role="tab"><i class="fas fa-bullhorn"></i><span>Active Bids</span></a>
        <a class="nav-link" id="profile-tab" data-toggle="pill" href="#profile" role="tab"><i class="fas fa-user"></i><span>Profile</span></a>
        <a class="nav-link" id="booking-history-tab" data-toggle="pill" href="#booking-history" role="tab"><i class="fas fa-history"></i><span>Booking History</span></a>
        <a class="nav-link" id="listings-tab" data-toggle="pill" href="#listings" role="tab"><i class="fas fa-home"></i><span>Listings</span></a>
        <a class="nav-link" id="guest-history-tab" data-toggle="pill" href="#guest-history" role="tab"><i class="fas fa-users"></i><span>Guest History</span></a>
        <a class="nav-link" id="security-tab" data-toggle="pill" href="#security" role="tab"><i class="fas fa-lock"></i><span>Security</span></a>
        <a class="nav-link" id="wallet-tab" data-toggle="pill" href="#wallet" role="tab"><i class="fas fa-wallet"></i><span>Wallet</span></a>
      </div>
      <h3 class="masthead-brand"><a href="{% url 'core:home' %}">localhost</a></h3>
    </div>
  </div>

  <div class="bg-light d-flex flex-column flex-grow-1 text-dark min-height-0">
    {% include "core/include/dashboard_header.html" %}
    <div class="tab-content d-flex flex-grow-1 min-height-0" id="v-pills-tabContent">
      <!-- Activity -->
      {% include "dashboard/active_bids.html" %}
      <!-- Profile -->
      {% include "dashboard/profile.html" %}
      <!-- Booking History -->
      {% include "dashboard/booking_history.html" %}
      <!-- Guest History -->
      {% include "dashboard/guest_history.html" %}
      <!-- Property Listings -->
      {% include "dashboard/property_listings.html" %}
      <!-- Settings -->
      {% include "dashboard/settings.html" %}
      <!-- Wallet -->
      {% include "dashboard/wallet.html" %}
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  var self = {{ user.id }};

  /* Registering bid event handler. */
  var handler = function(data) {
    $('#' + 'bid_item_' + data.property_item_id).text(data.amount);
    if (data.user_id == self) {
      $('#' + 'user_bid_item_' + data.property_item_id).text(data.amount);
    }
  }
  csocket.register_handler('bid', handler);

  {% if active_bids %}
  {% for item in active_bids %}
  /* Subscribing to each of the property events. */
  csocket.subscribe('property_item', {{ item.id }});
  {% endfor %}
  {% endif %}

</script>
{% endblock %}

localhost/dashboard/templates/dashboard/guest_history.html
<div class="p-2 flex-grow-1 justify-content-center tab-pane fade" id="guest-history" role="tabpanel">
  {% if guest_booking_list %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Booking</th>
        <th scope="col">Tenant</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <tbody>
      {% for booking in guest_booking_list %}
      <tr>
        <th scope="row">
          <div class="d-flex flex-column m-0">
            <a href="{{ booking.property_item.get_absolute_url }}" class="m-0"><h5 class="m-0">{{ booking.property_item }}</h5></a>
            <p class="m-0 font-weight-normal">{{ booking.property_item.property.address }}</p>
          </div>
        </th>
        <td class="align-middle"><a href="/profile/{{ booking.user_id }}" class="align-middle">{{ booking.user.first_name }}</a></td>
        <td class="align-middle">{{ booking.earliest_checkin_time|date }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="text-primary align-self-center">No guests have stayed with you yet</p>
  {% endif %}
</div>

localhost/dashboard/templates/dashboard/profile.html
{% load widget_tweaks %}
<div class="p-2 flex-grow-1 flex-column justify-content-center tab-pane fade" id="profile" role="tabpanel">
  <div class="panel p-2 mt-auto">
    <form id="change-bio" method="post" class="profile p-2 w-100" action="{% url 'dashboard:dashboard' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ forms.profile.bio.id_for_label }}"><h5 class="m-0">Personal Description</h5></label>
        {% render_field forms.profile.bio class="form-control mb-4" rows="3" %}
      </div>
      <div class="form-group">
        <label for="{{ forms.profile.dob.id_for_label }}"><h5 class="m-0">{{ forms.profile.dob.label }}</h5></label><br>
        {% render_field forms.profile.dob rows="3" %}
      </div>
      <div class="form-group mb-0">
        <label for="{{ forms.profile.gender.id_for_label }}"><h5 class="m-0">{{ forms.profile.gender.label }}</h5></label>
        {% render_field forms.profile.gender class="list-inline text-center" %}
      </div>
      <button name="action" class="btn btn-primary" type="submit" value="profile">Apply</button>
    </form>
  </div>
  <a href="{% url 'core:profile' user.id %}" class="align-self-end mt-auto"><button class="btn bg-accent text-white">View Public Profile</button></a>
</div>

localhost/dashboard/templates/dashboard/property_item_review.html
{% extends "core/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/header.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/footer.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/panel.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/leave_review.css" %}">
{% endblock %}

{% block title %} {{ block.super }} - Review {% endblock %}

{% block body_wrapped %}
{% include "core/include/header.html" %}

<div class="container panel p-0">
  <form method="post" class="m-0">
    {% csrf_token %}
    <img class="w-100" src="{{ property_item.images.first.img.url }}">
    <div class="p-4">
      <h4 class="mt-3">{{ property_item.title }}</h4>
      <strong class="text-success">{{ property_item.property.address }}</strong>
      <h5 class="mt-3">Star Rating</h5>
      <div>
        {% for _ in "xxxxx" %}
        <span class="fa fa-star" id="star-{{ forloop.counter0 }}" onclick="rating({{ forloop.counter }})"></span>
        {% endfor %}
      </div>
      {% render_field form.rating value="0" %}
      {% include "core/include/form_field.html" with form=form field=form.description %}
      <input type="submit" value="Submit" class="m-0 btn btn-success">
    </div>
  </form>
</div>

{% include "core/include/footer.html" %}
{% endblock %}
{% block js %}
<script>
  $('.fa-star').hover(
    function() {
      $(this).prevAll().addBack().css('color', 'orange');
    }, function() {
      $(this).prevAll().addBack().css('color', 'black');
    }
  );

  function rating(stars) {
    /*Add stars*/
    for (var i = 0; i < stars; i++) {
      $('#star-' + i).addClass('checked');
    }
    /*Remove extra stars*/
    for (var i = stars; i < 5; i++) {
      $('#star-' + i).removeClass('checked');
    }

    $('#id_rating').val(stars);
  }
</script>
{% endblock %}

localhost/dashboard/templates/dashboard/property_listings.html
<div class="p-2 flex-column flex-grow-1 justify-content-between tab-pane fade" id="listings" role="tabpanel">
  <div class="accordion w-100" id="accordion">
    {% for property in user.property_set.all %}
    <div class="card w-100">
      <div class="card-header" id="heading{{ forloop.counter }}" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
        <h5 class="mb-0 pl-2">
          <div class="d-inline">
            <a href="{{ property.get_absolute_url }}" class="d-inline text-left">
              <strong class="text-primary">{{ property.title }}</strong>
            </a>
            <small class="d-block text-secondary">
              {{ property.address }}
            </small>
          </div>
        </h5>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="align-self-end p-2">
    <a href="{% url 'dashboard:listing-create' %}" class="btn btn-raised text-white bg-accent">Add Property</a>
  </div>
</div>

localhost/dashboard/templates/dashboard/settings.html
<div class="p-2 flex-grow-1 justify-content-center tab-pane fade" id="security" role="tabpanel">
  <form id="change-password" method="post" class="panel">
    {% csrf_token %}
    <div class="form-group">
      {% for field in forms.password_change %}
      {% include "core/include/form_field.html" with form=forms.password_change field=field %}
      {% endfor %}
    </div>
    <div class="form-group">
      <button type="submit" value="password_change" name="action" class="btn btn-primary">Apply</button>
    </div>
  </form>
</div>

localhost/dashboard/templates/dashboard/wallet.html
<div class="p-2 flex-grow-1 justify-content-center tab-pane fade" id="wallet" role="tabpanel">
  <form id="change-wallet" method="post" class="wallet panel" action="{% url 'dashboard:dashboard' %}">
    <p><u>Current balance:</u> ${{ user.credits }}</p>
    {% csrf_token %}
    {% for field in forms.wallet %}
    {% include "core/include/form_field.html" with form=forms.wallet field=field %}
    {% endfor %}
    <div class="form-group">
      <button type="submit" name="action" class="btn btn-primary" value="wallet">Add</button>
    </div>
  </form>
</div>