localhost/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path(
        'property/<int:pk>',
        views.PropertyDetailView.as_view(),
        name='property-detail'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile'),
    path(
        'about',
        TemplateView.as_view(template_name='core/about_us.html'),
        name='about'),
]

handler404 = 'core.views.PageNotFoundView'

localhost/messaging/urls.py
from django.urls import path

from . import views

app_name = 'messaging'

urlpatterns = [
    path('', views.MessagingView.as_view(), name='messages'),
]

localhost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('localhost.core.urls')),
    path('', include('localhost.authentication.urls')),
    path('dashboard/', include('localhost.dashboard.urls')),
    path('messages/', include('localhost.messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

localhost/authentication/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.mail import send_mail
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


def avatar_img_path(instance, filename):
    return f"user_{instance.id}/avatar_{filename}"


class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    A concrete class implementing a fully featured User model with
    admin-compliant permissions.
    Email, first name, last name and password are required. Other fields are
    optional.
    """
    DEFAULT_AVATAR_PATH = 'default/avatar-placeholder.png'
    first_name = models.CharField(_('first name'), max_length=30, blank=False)
    last_name = models.CharField(_('last name'), max_length=150, blank=False)
    email = models.EmailField(_('email address'), unique=True, blank=False)
    avatar = models.ImageField(
        _('avatar'), upload_to=avatar_img_path, default=DEFAULT_AVATAR_PATH)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'),
    )
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )
    bio = models.CharField(
        _('bio'),
        max_length=100,
        null=True,
        blank=True,
        help_text=_('Short description of yourself'))
    dob = models.DateField(_('date of birth'), null=True)
    gender = models.CharField(
        _('gender'),
        max_length=1,
        choices=GENDER_CHOICES,
        null=True,
        default=None)
    credits = models.BigIntegerField(
        _('credits'), default=0, validators=[MinValueValidator(0)])
    objects = UserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    @property
    def full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    @property
    def short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.email

localhost/core/models.py
import json
import logging

from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import IntegrityError, models
from django.db.models import F, Q
from django.db.models.signals import m2m_changed, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_celery_beat.models import (CrontabSchedule, PeriodicTask,
                                       PeriodicTasks)

logger = logging.getLogger(__name__)


class Amenity(models.Model):
    item = models.CharField(max_length=15, unique=True)
    icon = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                regex=r'^fa-[\w]*',
                message=_('Icon class must starts with \"fa-\"'))
        ],
        help_text=_('Font Awesome glyph class.'))

    class Meta:
        verbose_name_plural = 'amenities'

    def __str__(self):
        return f"{self.item}"


class BiddingSession(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()

    @classmethod
    def current_session_of(cls, property_item):
        """
        Helper function to return current session a property item is in.
        """
        now = timezone.localtime().time()
        qs1 = cls.objects.filter(
            Q(start_time__lte=F('end_time')),
            Q(start_time__lte=now),
            end_time__gte=now,
            propertyitem=property_item)
        qs2 = cls.objects.filter(
            Q(start_time__gt=F('end_time')),
            Q(start_time__lte=now)
            | Q(end_time__gte=now),
            propertyitem=property_item)
        return qs1.union(qs2).first()

    def __str__(self):
        return f"""{self.start_time.strftime('%I:%M %p')} - {self.end_time.strftime('%I:%M %p')}"""


class Sin(models.Func):
    function = 'SIN'


class Cos(models.Func):
    function = 'COS'


class Acos(models.Func):
    function = 'ACOS'


class Radians(models.Func):
    function = 'RADIANS'


class DistanceManager(models.Manager):
    """
    Custom manager that adds functions related to geographical distance.
    """

    def within(self, latitude, longitude):
        """
        Returns the distance between two locations given latitude and
        longitude. The distance is calculated using Haversine Formula. See
        https://en.wikipedia.org/wiki/Haversine_formula
        The model that this manager handles must have a latitude and longitutde
        field.

        Usage:
        >>> class Foo(models.Model):
        >>>     latitude = models.DecimalField()
        >>>     longitude = models.DecimalField()
        >>>     objects = DistanceManager()

        >>> Foo.objects.within(lat, lng)
        <QuerySet [<Foo: ...>]>

        Args:
            latitude: Latitude of the given location
            longitude: Longitude of the given location

        Returns:
            A queryset with annotated distance between the given location and
            objects
        """
        radlat = Radians(latitude)  # given latitude
        radlong = Radians(longitude)  # given longitude
        radflat = Radians(models.F('latitude'))
        radflong = Radians(models.F('longitude'))

        # 6371 is for km. Use 3959 for miles
        expr = 6371 * Acos(
            Cos(radlat) * Cos(radflat) * Cos(radflong - radlong) +
            Sin(radlat) * Sin(radflat))

        return self.get_queryset().annotate(distance=expr)


class Property(models.Model):
    host = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(
        _('title'), max_length=100, help_text=_('Character limit: 100'))
    description = models.TextField(
        _('description'), max_length=600, help_text=_('Character limit: 600'))
    address = models.CharField(
        _('address'), max_length=200, help_text=_('Address of this property.'))
    latitude = models.DecimalField(
        max_digits=10, decimal_places=7, editable=False)
    longitude = models.DecimalField(
        max_digits=10, decimal_places=7, editable=False)
    earliest_checkin_time = models.TimeField(
        _('earliest check-in time'),
        help_text=_('Earliest time a guest can check-in.'))
    latest_checkin_time = models.TimeField(
        _('latest check-in time'),
        help_text=_('Latest time a guest can check-in.'))

    objects = DistanceManager()

    class Meta:
        verbose_name_plural = 'properties'

    def get_absolute_url(self):
        return reverse('core:property-detail', args=[str(self.id)])

    def __str__(self):
        return f"Property: {self.title} owned by {self.host} ({self.longitude}, {self.latitude})"


class PropertyItem(models.Model):
    property = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name='property_item')
    title = models.CharField(
        _('title'), max_length=100, help_text=_('Character limit: 100'))
    description = models.TextField(
        _('description'), max_length=600, help_text=_('Character limit: 600'))
    buyout_price = models.PositiveIntegerField(
        _('buyout price'), help_text=_('Buyout price of the auction.'))
    min_price = models.PositiveIntegerField(
        _('min price'), help_text=_('Starting price of the auction.'))
    session = models.ManyToManyField(
        BiddingSession,
        verbose_name=_('bidding session'),
        blank=True,
        help_text=_('Choose a session to enable bidding during those times.'))
    amenities = models.ManyToManyField(
        Amenity, blank=True, help_text=_('Amenities in this place.'))
    capacity = models.PositiveIntegerField()
    available = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('core:property-detail', args=[str(self.property.id)])

    def __str__(self):
        return f"{self.title}"


def property_item_img_path(instance, filename):
    """
    File will be uploaded to
    MEDIA_ROOT/user_<id>/property_item_<property_item_id>/<filename>
    """
    return f"user_{instance.property_item.property.host.id}/property_item_{instance.property_item.id}/{filename}"


def property_img_path(instance, filename):
    """
    File will be uploaded to
    MEDIA_ROOT/user_<id>/property_<property_item_id>/<filename>
    """
    return f"user_{instance.property.host.id}/property_{instance.property.id}/{filename}"


class PropertyImage(models.Model):
    property = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=property_img_path)


class PropertyItemImage(models.Model):
    property_item = models.ForeignKey(
        PropertyItem, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=property_item_img_path)


class Bid(models.Model):
    property_item = models.ForeignKey(
        PropertyItem, on_delete=models.CASCADE, related_name='bids')
    bidder = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()

    class Meta:
        get_latest_by = 'amount'


class Booking(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    property_item = models.ForeignKey(PropertyItem, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(_('price'))
    earliest_checkin_time = models.DateTimeField(_('earliest check-in time'))
    latest_checkin_time = models.DateTimeField(_('latest check-in time'))

    def __str__(self):
        return f"{self.user} booked {self.property_item}"


class PropertyItemReview(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(6)])
    description = models.TextField(_('description'))


class Notification(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    OUTBID = 'O'
    WON_BID = 'W'
    BUYOUT = 'B'
    MESSAGE_CHOICES = ((OUTBID, 'You have been outbid!'),
                       (WON_BID, 'You have won your auction!'),
                       (BUYOUT,
                        'The item you were bidding on was bought out!'))
    message = models.CharField(
        _('message'),
        max_length=1,
        choices=MESSAGE_CHOICES,
    )
    property_item = models.ForeignKey(PropertyItem, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)


@receiver(m2m_changed, sender=PropertyItem.session.through)
def property_item_m2m_changed(instance, action, pk_set, **kwargs):
    """
    Add/remove cleanup task when session has been added to/removed from the
    property item.
    """
    sessions = BiddingSession.objects.filter(id__in=pk_set)
    if action == 'post_add':
        for i, session in enumerate(sessions):
            schedule, _ = CrontabSchedule.objects.get_or_create(
                minute=session.end_time.minute, hour=session.end_time.hour)
            PeriodicTask.objects.get_or_create(
                crontab=schedule,
                task='localhost.core.tasks.cleanup_bids',
                name=f'PropertyItem-{instance.id} bids cleanup {i}',
                args=json.dumps([instance.id]))
    elif action == 'post_remove':
        names = [
            f'PropertyItem-{instance.id} bids cleanup {i}'
            for session in sessions
        ]
        PeriodicTask.objects.filter(name__in=names).delete()


@receiver(pre_save, sender=PropertyItem)
def property_item_pre_save(instance, **kwargs):
    """
    Enable bids every day at 12nn.
    """
    schedule, _ = CrontabSchedule.objects.get_or_create(hour=12, minute=0)
    try:
        PeriodicTask.objects.get_or_create(
            crontab=schedule,
            task='localhost.core.tasks.enable_bids',
            name=f'Daily bids enable {instance.id}',
            args=json.dumps([instance.id]))
    except IntegrityError:

localhost/messaging/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import ListView

from localhost.messaging.models import Message

User = get_user_model()


class MessagingView(LoginRequiredMixin, ListView):
    template_name = 'messaging/messaging.html'
    model = Message

    def get_context_data(self, **kwargs):
        """
        Pass conversations to context.

        context['conversations']: [(user, [messages]), (user, [messages]), ...]
        """
        context = super().get_context_data(**kwargs)
        try:
            recipient = User.objects.get(pk=self.request.GET.get('recipient'))
            context['recipient'] = recipient
        except User.DoesNotExist:
            pass

        auth_user = self.request.user
        messages = self.model.objects.filter(
            Q(sender=auth_user) | Q(recipient=auth_user))
        contacts = User.objects \
            .filter(
                Q(sent_messages__pk__in=messages.values('pk'))
                | Q(received_messages__pk__in=messages.values('pk'))) \
            .exclude(pk=auth_user.pk).distinct()
        conversations = [(user,
                          messages.filter(Q(sender=user) | Q(recipient=user)))
                         for user in contacts]
        context['conversations'] = conversations
        return context

localhost/core/templates/core/about_us.html
{% extends "core/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/header.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/footer.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/panel.css" %}">
{% endblock %}

{% block body_wrapped %}
{% include "core/include/header.html" %}
<div class="panel container d-flex flex-column justify-content-center">
  <h1>We are the undergrads.</h1>
</div>
{% include "core/include/footer.html" %}
{% endblock %}

localhost/core/templates/core/home.html
{% extends "core/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/header.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/footer.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/gmaps.css" %}">
{% if user.is_authenticated %}
<link rel="stylesheet" type="text/css" href="{% static "core/css/home.css" %}">
{% else %}
<link rel="stylesheet" type="text/css" href="{% static "core/css/splash.css" %}">
{% endif %}
{% endblock %}

{% block body_wrapped %}
{% include "core/include/header.html" %}
<main role="main">
  <ul class="tag-lines">
    <li>
      {% if user.is_authenticated %}
      {% if last_booking %}
      <h1>We hope you enjoyed your stay at {{ last_booking.property_item.property.address }}!</h1>
      {% else %}
      <h1>Welcome to localhost!</h1>
      {% endif %}
      {% else %}
      <h1 class="tag-head">Welcome to the next generation of lodging</h1>
      {% endif %}
    </li>
    <li>
      {% if user.is_authenticated %}
      {% if last_booking %}
      <h4>Are you ready for your next adventure?</h4>
      {% else %}
      <h1>We hope you enjoy your stay</h1>
      {% endif %}
      {% else %}
      <h4>Search &bull; Bid &bull; Stay</h4>
      {% endif %}
    </li>
  </ul>
  <div class="input-group stylish-input-group">
    {% if user.is_authenticated %}
    <input id="suburb_search" type="text" class="form-control py-2" placeholder="Where would you like to go?">
    {% else %}
    <input id="suburb_search" type="text" class="form-control py-2" placeholder="Try searching for 'Kingsford'">
    {% endif %}
  </div>
  <form id="form-search" method="get" action="{% url 'core:search-results' %}">
    <input type="hidden" id="suburb_search_lat" name="lat" value="">
    <input type="hidden" id="suburb_search_lng" name="lng" value="">
    <input type="hidden" id="full_address" name="addr" value="">
  </form>
</main>
{% include "core/include/footer.html" %}
{% endblock %}

{% block js %}
<script>
  function activateSearchCallback() {
    activateSearch('suburb_search', 'suburb_search_lat', 'suburb_search_lng', 'full_address','form-search');
  }
</script>
<script type="text/javascript" src="{% static "core/js/search_geolocation.js" %}"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ GMAPS_KEY }}&libraries=places&callback=activateSearchCallback"></script>
{% endblock %}

localhost/core/templates/core/property_detail.html
{% extends "core/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/header.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/footer.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/property.css" %}">
{% endblock %}

{% block body_wrapped %}
{% include "core/include/header.html" %}
<div class="container p-4">
  <div id="property-carousel" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
      {% with "https://via.placeholder.com/600x300?text=No images" as placeholder_image %}
      {% for image in property.images.all %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img class="d-block w-100" src="{{ image.img.url }}" alt="slide-{{ forloop.counter }}">
      </div>
      {% empty %}
      <div class="carousel-item active">
        <img class="d-block w-100" src="{{ placeholder_image }}" alt="slide-1">
      </div>
      {% endfor %}
      {% endwith %}
    </div>
    <a class="carousel-control-prev" href="#property-carousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#property-carousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <!-- Description and amneties -->
  <div class="d-flex">
    <div class="card w-100">
      <div class="card-body d-flex justify-content-between pb-3">
        <div class="d-flex flex-column align-items-start">
          <h3>{{ property.title }}</h3>
          <div class="d-flex flex-row align-items-center">
            <strong class="text-success">{{ property.address }}</strong>
          </div>
          <p class="mb-1 d-flex flex-column flex-grow-1">{{ property.description }}</p>
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary m-0" data-toggle="modal" data-target="#map-modal">
            Map
          </button>
        </div>
        <div class="d-flex flex-column flex-grow-1 align-items-center justify-content-center host">
          <img class="avatar" src="{{ property.host.avatar.url }}">
          {{ property.host.short_name }}
          <div class="input-group">
            <div class="input-group-prepend mx-auto">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Contact</button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'core:profile' property.host.id %}">View host profile</a>
                <form id="id" class="dropdown-item m-0 py-0" method="get" action="{% url 'messaging:messages' %}">
                  <input type="hidden" id="recipient" name="recipient" value="{{ property.host_id }}">
                  <button class="dropdown-item p-0" type="submit">Send a message</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="align-self-center d-flex flex-column justify-content-between h-100">
      <!-- Map modal -->
      {% include "core/include/property/property_map_modal.html" %}
    </div>
  </div>
  <!-- Property item listings -->
  {% include "core/include/property/property_items.html" %}
</div>
{% include "core/include/footer.html" %}
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static "core/js/property/mobile_modal_hide.js" %}"></script>
<script type="text/javascript" src="{% static "core/js/countdown.js" %}"></script>
<script>
  /* Setting the countdown for each of the active auction items. */
  var session_end = new Date('{% now "F j, Y" %} {{ session_end|time:"H:i:s" }}').getTime();
  register_countdown('countdown', session_end, 'CLOSED');
</script>
<script>
  /* Registering realtime buyout event handler. */
  var buyout_handler = function(data) {
    $('#bidding-module-' + data.property_item_id + ' button').prop('disabled', true);
    $('#bidding-module-' + data.property_item_id + ' input').prop('disabled', true);
    $('#bidding-module-' + data.property_item_id + ' .alert').text("Bought out!");
    $('#bidding-module-' + data.property_item_id + ' .alert').show();
  }
  csocket.register_handler('buyout', buyout_handler)

  $('.buyout-button').click(function() {
    $('#buyout-confirm-' + $(this).val()).modal({backdrop: 'static', show: true});
  });

  $('.buyout-confirm').click(function() {
    csocket.buyout($(this).val());
    $('#buyout-confirm-' + $(this).val()).modal('hide');
  });

  /* Registering realtime bid handler event handler. */
  var bid_handler = function(data) {
    var new_bid = data.amount;
    $('#bid-current-' + data.property_item_id).text('$' + new_bid);
    $('#bid-current-modal-' + data.property_item_id).text('Current bid: $' + new_bid);

    if (data.user_id == {{ user.id }}) {
      $('#highest-bidder').html('You have the highest bid!');
      $('#highest-bidder').addClass('font-weight-bold');
    } else {
      $('#highest-bidder').html('Someone else has the highest bid!');
      $('#highest-bidder').removeClass('font-weight-bold');
    }
  }
  csocket.register_handler('bid', bid_handler);

  /* Registering listener for property events. */
  {% for property_item in property.property_item.all %}
  csocket.subscribe('property_item', {{ property_item.id }});
  {% endfor %}

  /* Registering listener for alerts. */
  var alert_handler = function(data) {
    $('#bidding-module-' + data.property_item_id + ' .alert').text(data.description);
    $('#bidding-module-' + data.property_item_id + ' .alert').show();
  }
  csocket.register_handler('alert', alert_handler);
</script>
<script>
  /* Catching errors client side for bidding. */
  function sendBid (button) {
    var amount = $('#amount-ttb-' + button.id).val()
    if (amount) {
      if (!isNaN(amount)) {
        csocket.bid(button.id, amount);
      }
    }
  }
</script>
<script>
  /* Displaying map when button registers function call. */
  function initMap() {
    var property = {lat: {{ property.latitude }}, lng: {{ property.longitude }}};
    var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 14, center: property});
    var marker = new google.maps.Marker({position: property, map: map});
  }
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ GMAPS_KEY }}&libraries=places&callback=initMap"></script>
<script>
  /* Event triggered when the modal is finished disappearing off the screen. */
  $(document).on('hidden.bs.modal', '.modal', function () {
    $('.modal:visible').length && $(document.body).addClass('modal-open');
  });
</script>
{% endblock %}

localhost/core/templates/core/public_profile.html
{% extends "core/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/header.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/footer.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/review.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/panel.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/public_profile.css" %}">
{% endblock %}

{% block main-container %}
<div class="container-fluid d-flex flex-column justify-content-between p-0">
{% endblock %}

{% block body_wrapped %}
{% include "core/include/header.html" %}
<div class="card mb-4 p-4 align-self-center">
  <div class="row card-body pl-0">
    <div class="col-md-6">
      <img class="avatar mx-auto d-block" src="{{ user.avatar.url }}">
    </div>
    <div class="d-flex col-md-6">
      <div class="d-flex flex-column flex-grow-1 justify-content-between">
        <h1>{{ user.full_name }}</h1>
        {% if user.gender %}
        <h6>{{ user.get_gender_display }}</h6>
        {% endif %}
        {% if age %}
        <h6>{{ age }}</h6>
        {% endif %}
        <p>
          {% if user.bio %}
          {{ user.bio }}
          {% else %}
          N/A
          {% endif %}
        </p>
        <div class="d-flex flex-row flex-grow-1">
          <button class="btn btn-primary view-item" data-toggle="modal" data-target="#properties">View Properties</button>
          <form id="id" class="m-0 align-self-center" method="get" action="{% url 'messaging:messages' %}">
            <input type="hidden" id="recipient" name="recipient" value="{{ user.id }}">
            <button class="btn btn-primary" type="submit">Send a Message</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<button type="button" class="btn btn-warning bmd-btn-fab modal-close">
  <i class="fas fa-times-circle"></i>
</button>
<div class="modal fade" id="properties" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-accent px-4 py-3">
        <h3 class="modal-title text-white">Properties</h3>
        <button type="button" class="close align-self-center m-0 p-0 pr-1" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for property in user.property_set.all %}
        <div class="card w-100">
          <div class="card-header" id="heading{{ forloop.counter }}" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
            <h5 class="mb-0 pl-2">
              <div class="d-inline">
                <a href="{{ property.get_absolute_url }}" class="d-inline text-left">
                  <strong class="text-primary">{{ property.title }}</strong>
                </a>
                <small class="d-block text-secondary">
                  {{ property.address }}
                </small>
              </div>
            </h5>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% include "core/include/footer.html" %}
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static "core/js/property/mobile_modal_hide.js" %}"></script>
{% endblock %}