localhost/authentication/urls.py
from django.urls import include, path
from django.views.defaults import page_not_found

from . import views

app_name = 'authentication'

urlpatterns = [
    # override default view
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    # disable default password change view(s)
    path('accounts/password_change/', page_not_found,
         {'exception': Exception()}),
    path('accounts/password_change/done', page_not_found,
         {'exception': Exception()}),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.SignUpView.as_view(), name='register'),
]

localhost/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path(
        'property/<int:pk>',
        views.PropertyDetailView.as_view(),
        name='property-detail'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'),
    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile'),
    path(
        'about',
        TemplateView.as_view(template_name='core/about_us.html'),
        name='about'),
]

handler404 = 'core.views.PageNotFoundView'

localhost/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path(
        '',
        views.DashboardView.as_view(),
        name='dashboard'),
    path('listing/add/', views.ListingCreate.as_view(), name='listing-create'),
    path(
        'listing/<int:pk>/delete',
        views.ListingDelete.as_view(),
        name='listing-delete'),
    path(
        'review/listing/<int:pk>',
        views.ListingReviewView.as_view(),
        name='listing-review')
]

localhost/messaging/urls.py
from django.urls import path

from . import views

app_name = 'messaging'

urlpatterns = [
    path('', views.MessagingView.as_view(), name='messages'),
]

localhost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('localhost.core.urls')),
    path('', include('localhost.authentication.urls')),
    path('dashboard/', include('localhost.dashboard.urls')),
    path('messages/', include('localhost.messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

localhost/core/models.py
import json
import logging

from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import IntegrityError, models
from django.db.models import F, Q
from django.db.models.signals import m2m_changed, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_celery_beat.models import (CrontabSchedule, PeriodicTask,
                                       PeriodicTasks)

logger = logging.getLogger(__name__)


class Amenity(models.Model):
    item = models.CharField(max_length=15, unique=True)
    icon = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                regex=r'^fa-[\w]*',
                message=_('Icon class must starts with \"fa-\"'))
        ],
        help_text=_('Font Awesome glyph class.'))

    class Meta:
        verbose_name_plural = 'amenities'

    def __str__(self):
        return f"{self.item}"


class BiddingSession(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()

    @classmethod
    def current_session_of(cls, property_item):
        """
        Helper function to return current session a property item is in.
        """
        now = timezone.localtime().time()
        qs1 = cls.objects.filter(
            Q(start_time__lte=F('end_time')),
            Q(start_time__lte=now),
            end_time__gte=now,
            propertyitem=property_item)
        qs2 = cls.objects.filter(
            Q(start_time__gt=F('end_time')),
            Q(start_time__lte=now)
            | Q(end_time__gte=now),
            propertyitem=property_item)
        return qs1.union(qs2).first()

    def __str__(self):
        return f"""{self.start_time.strftime('%I:%M %p')} - {self.end_time.strftime('%I:%M %p')}"""


class Sin(models.Func):
    function = 'SIN'


class Cos(models.Func):
    function = 'COS'


class Acos(models.Func):
    function = 'ACOS'


class Radians(models.Func):
    function = 'RADIANS'


class DistanceManager(models.Manager):
    """
    Custom manager that adds functions related to geographical distance.
    """

    def within(self, latitude, longitude):
        """
        Returns the distance between two locations given latitude and
        longitude. The distance is calculated using Haversine Formula. See
        https://en.wikipedia.org/wiki/Haversine_formula
        The model that this manager handles must have a latitude and longitutde
        field.

        Usage:
        >>> class Foo(models.Model):
        >>>     latitude = models.DecimalField()
        >>>     longitude = models.DecimalField()
        >>>     objects = DistanceManager()

        >>> Foo.objects.within(lat, lng)
        <QuerySet [<Foo: ...>]>

        Args:
            latitude: Latitude of the given location
            longitude: Longitude of the given location

        Returns:
            A queryset with annotated distance between the given location and
            objects
        """
        radlat = Radians(latitude)  # given latitude
        radlong = Radians(longitude)  # given longitude
        radflat = Radians(models.F('latitude'))
        radflong = Radians(models.F('longitude'))

        # 6371 is for km. Use 3959 for miles
        expr = 6371 * Acos(
            Cos(radlat) * Cos(radflat) * Cos(radflong - radlong) +
            Sin(radlat) * Sin(radflat))

        return self.get_queryset().annotate(distance=expr)


class Property(models.Model):
    host = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(
        _('title'), max_length=100, help_text=_('Character limit: 100'))
    description = models.TextField(
        _('description'), max_length=600, help_text=_('Character limit: 600'))
    address = models.CharField(
        _('address'), max_length=200, help_text=_('Address of this property.'))
    latitude = models.DecimalField(
        max_digits=10, decimal_places=7, editable=False)
    longitude = models.DecimalField(
        max_digits=10, decimal_places=7, editable=False)
    earliest_checkin_time = models.TimeField(
        _('earliest check-in time'),
        help_text=_('Earliest time a guest can check-in.'))
    latest_checkin_time = models.TimeField(
        _('latest check-in time'),
        help_text=_('Latest time a guest can check-in.'))

    objects = DistanceManager()

    class Meta:
        verbose_name_plural = 'properties'

    def get_absolute_url(self):
        return reverse('core:property-detail', args=[str(self.id)])

    def __str__(self):
        return f"Property: {self.title} owned by {self.host} ({self.longitude}, {self.latitude})"


class PropertyItem(models.Model):
    property = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name='property_item')
    title = models.CharField(
        _('title'), max_length=100, help_text=_('Character limit: 100'))
    description = models.TextField(
        _('description'), max_length=600, help_text=_('Character limit: 600'))
    buyout_price = models.PositiveIntegerField(
        _('buyout price'), help_text=_('Buyout price of the auction.'))
    min_price = models.PositiveIntegerField(
        _('min price'), help_text=_('Starting price of the auction.'))
    session = models.ManyToManyField(
        BiddingSession,
        verbose_name=_('bidding session'),
        blank=True,
        help_text=_('Choose a session to enable bidding during those times.'))
    amenities = models.ManyToManyField(
        Amenity, blank=True, help_text=_('Amenities in this place.'))
    capacity = models.PositiveIntegerField()
    available = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('core:property-detail', args=[str(self.property.id)])

    def __str__(self):
        return f"{self.title}"


def property_item_img_path(instance, filename):
    """
    File will be uploaded to
    MEDIA_ROOT/user_<id>/property_item_<property_item_id>/<filename>
    """
    return f"user_{instance.property_item.property.host.id}/property_item_{instance.property_item.id}/{filename}"


def property_img_path(instance, filename):
    """
    File will be uploaded to
    MEDIA_ROOT/user_<id>/property_<property_item_id>/<filename>
    """
    return f"user_{instance.property.host.id}/property_{instance.property.id}/{filename}"


class PropertyImage(models.Model):
    property = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=property_img_path)


class PropertyItemImage(models.Model):
    property_item = models.ForeignKey(
        PropertyItem, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=property_item_img_path)


class Bid(models.Model):
    property_item = models.ForeignKey(
        PropertyItem, on_delete=models.CASCADE, related_name='bids')
    bidder = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()

    class Meta:
        get_latest_by = 'amount'


class Booking(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    property_item = models.ForeignKey(PropertyItem, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(_('price'))
    earliest_checkin_time = models.DateTimeField(_('earliest check-in time'))
    latest_checkin_time = models.DateTimeField(_('latest check-in time'))

    def __str__(self):
        return f"{self.user} booked {self.property_item}"


class PropertyItemReview(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(6)])
    description = models.TextField(_('description'))


class Notification(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    OUTBID = 'O'
    WON_BID = 'W'
    BUYOUT = 'B'
    MESSAGE_CHOICES = ((OUTBID, 'You have been outbid!'),
                       (WON_BID, 'You have won your auction!'),
                       (BUYOUT,
                        'The item you were bidding on was bought out!'))
    message = models.CharField(
        _('message'),
        max_length=1,
        choices=MESSAGE_CHOICES,
    )
    property_item = models.ForeignKey(PropertyItem, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)


@receiver(m2m_changed, sender=PropertyItem.session.through)
def property_item_m2m_changed(instance, action, pk_set, **kwargs):
    """
    Add/remove cleanup task when session has been added to/removed from the
    property item.
    """
    sessions = BiddingSession.objects.filter(id__in=pk_set)
    if action == 'post_add':
        for i, session in enumerate(sessions):
            schedule, _ = CrontabSchedule.objects.get_or_create(
                minute=session.end_time.minute, hour=session.end_time.hour)
            PeriodicTask.objects.get_or_create(
                crontab=schedule,
                task='localhost.core.tasks.cleanup_bids',
                name=f'PropertyItem-{instance.id} bids cleanup {i}',
                args=json.dumps([instance.id]))
    elif action == 'post_remove':
        names = [
            f'PropertyItem-{instance.id} bids cleanup {i}'
            for session in sessions
        ]
        PeriodicTask.objects.filter(name__in=names).delete()


@receiver(pre_save, sender=PropertyItem)
def property_item_pre_save(instance, **kwargs):
    """
    Enable bids every day at 12nn.
    """
    schedule, _ = CrontabSchedule.objects.get_or_create(hour=12, minute=0)
    try:
        PeriodicTask.objects.get_or_create(
            crontab=schedule,
            task='localhost.core.tasks.enable_bids',
            name=f'Daily bids enable {instance.id}',
            args=json.dumps([instance.id]))
    except IntegrityError:

localhost/core/templates/core/include/dashboard_header.html
{% url 'messaging:messages' as messages %}
{% url 'dashboard:dashboard' as dashboard %}

<header class="masthead p-3">
  <nav class="nav nav-masthead flex-grow-1">
    {% if not user.is_authenticated %}
    <a class="nav-link" href="{% url 'authentication:register' %}">Register</a>
    <a class="nav-link" href="{% url 'authentication:login' %}">Log in</a>
    {% else %}
    <button class="btn navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#contacts">
      <i class="fas fa-user-friends"></i>
    </button>
    <a class="nav-link btn-home" href="{% url 'core:home' %}"><h5 class="m-0"><i class="fas fa-home"></i></h5></a>
    <button class="btn navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#settings">
      <i class="fas fa-ellipsis-v"></i>
    </button>
    <div class="collapse navbar-collapse" id="settings">
      <div id="notifications" class="btn-group">
        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Notifications
        </button>
        <div class="dropdown-menu">
          {% if notifications %}
          {% for notification in notifications %}
          <div class="d-flex flex-row">
            <a class="dropdown-item" href="/property/{{ notification.property_item.id }}">{{ notification.get_message_display }}</a>
            <button id="button-notification-{{ notification.id }}" class="notification-btn btn btn-primary" style="color:black !important;">clear</button>
          </div>
          {% endfor %}
          {% else %}
          <a id="notification-none" class="dropdown-item">None</a>
          {% endif %}
        </div>
      </div>
      {% if request.path == messages %}
      <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
      {% else %}
      <a class="nav-link" href="{% url 'messaging:messages' %}">Messages</a>
      {% endif %}
      <a class="nav-link" href="{% url 'authentication:logout' %}">Log out</a>
      {% endif %}
    </div>
  </nav>
</header>

localhost/core/templates/core/include/footer.html
<footer class="mastfoot p-3">
  <div class="inner">
    <nav class="nav nav-mastfoot justify-content-center">
      <a class="nav-link" href="{% url 'core:about' %}">About Us</a>
      <a class="nav-link" href="https://bitbucket.org/jtalowell/localhost/">BitBucket</a>
    </nav>
  </div>
</footer>

localhost/core/templates/core/include/form_field.html
{% comment %}
Populate a standard form field.

Context args:
  form: form where the field belongs to
  field: the form field to be populated.
{% endcomment %}
{% load widget_tweaks %}

<div class="form-group {{ field_extra_css }}">
  <label for="{{ field.id_for_label }}" class="sr-only">{{ field.label }}</label>
  {% if form.is_bound %}
    {% if field.errors %}
      {% render_field field class="form-control is-invalid" placeholder=field.label %}
      {% for error in field.errors %}
        <div class="invalid-feedback">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% else %}
      {% render_field field class="form-control is-valid" placeholder=field.label %}
    {% endif %}
  {% else %}
    {% render_field field class="form-control" placeholder=field.label %}
  {% endif %}

  {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text|safe }}</small>
  {% endif %}
</div>

localhost/core/templates/core/include/header.html
{% url 'messaging:messages' as messages %}
{% url 'dashboard:dashboard' as dashboard %}

<header class="masthead p-3">
  {% if request.path != messages and request.path != dashboard %}
  <h3 class="masthead-brand"><a href="{% url 'core:home' %}">localhost</a></h3>
  {% endif %}
  <nav class="nav nav-masthead flex-grow-1">
    {% if not user.is_authenticated %}
    <a class="nav-link order-lg-2" href="{% url 'authentication:register' %}">Register</a>
    <a class="nav-link order-lg-3" href="{% url 'authentication:login' %}">Log in</a>
    {% else %}
    {% if request.path == messages or request.path == dashboard %}
    <a class="nav-link mr-auto" href="{% url 'core:home' %}"><h5 class="m-0"><i class="fas fa-home"></i></h5></a>
    {% endif %}
    <div id="notifications" class="btn-group order-lg-2">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Notifications
      </button>
      <div class="dropdown-menu">
        {% if notifications %}
        {% for notification in notifications %}
        <div class="d-flex flex-row">
          <a class="dropdown-item" href="/property/{{ notification.property_item.id }}">{{ notification.get_message_display }}</a>
          <button id="button-notification-{{ notification.id }}" class="notification-btn btn btn-primary" style="color:black !important;">clear</button>
        </div>
        {% endfor %}
        {% else %}
        <a id="notification-none" class="dropdown-item">None</a>
        {% endif %}
      </div>
    </div>
    {% if request.path != messages %}
    <a class="nav-link  order-lg-3" href="{% url 'messaging:messages' %}">Messages</a>
    {% endif %}
    {% if request.path != dashboard %}
    <a class="nav-link order-lg-4" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
    {% endif %}
    <a class="nav-link order-lg-5" href="{% url 'authentication:logout' %}">Log out</a>
    {% endif %}
  </nav>
</header>

localhost/core/templates/core/include/search_filter.html
<div class="d-flex flex-column justify-content-center px-md-4">
  <div class="input-group stylish-input-group">
    <input id="suburb_search" type="text" class="form-control" placeholder="Where would you like to go?">
    <div class="input-group-append">
      <span class="input-group-text"><i class="fa fa-search"></i></span>
    </div>
  </div>
  <form id="form-search" class="mb-0 mt-2" method="get" action="{% url 'core:search-results' %}">
    <input type="hidden" id="suburb_search_lat" name="lat" value="">
    <input type="hidden" id="suburb_search_lng" name="lng" value="">
    <input type="hidden" id="full_addr" name="addr" value="">
    <ul class="list-inline d-inline">
      <li class="list-inline-item">
        <select id="guests" name="guests" class="btn filter-option dropdown-toggle my-0" type="button" data-toggle="dropdown">
          <option disabled selected><span>Guests</span></option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5+</option>
        </select>
      </li>
      <li class="list-inline-item">
        <div class="btn-group-toggle" data-toggle="buttons">
          <label class="btn filter-option">
            <input id="bidding-active" name="bidding-active" type="checkbox" class="d-none" autocomplete="off"> Bidding Active
          </label>
        </div>
      </li>
      <li class="list-inline-item">
      </li>
    </ul>
    <button class="btn btn-raised font-weight-bold float-right text-white bg-background">Apply</button>
  </form>
</div> 