localhost/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path(
        '',
        views.DashboardView.as_view(),
        name='dashboard'),
    path('listing/add/', views.ListingCreate.as_view(), name='listing-create'),
    path(
        'listing/<int:pk>/delete',
        views.ListingDelete.as_view(),
        name='listing-delete'),
    path(
        'review/listing/<int:pk>',
        views.ListingReviewView.as_view(),
        name='listing-review')
]

localhost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('localhost.core.urls')),
    path('', include('localhost.authentication.urls')),
    path('dashboard/', include('localhost.dashboard.urls')),
    path('messages/', include('localhost.messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

localhost/core/models.py
import json
import logging

from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import IntegrityError, models
from django.db.models import F, Q
from django.db.models.signals import m2m_changed, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_celery_beat.models import (CrontabSchedule, PeriodicTask,
                                       PeriodicTasks)

logger = logging.getLogger(__name__)


class Amenity(models.Model):
    item = models.CharField(max_length=15, unique=True)
    icon = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                regex=r'^fa-[\w]*',
                message=_('Icon class must starts with \"fa-\"'))
        ],
        help_text=_('Font Awesome glyph class.'))

    class Meta:
        verbose_name_plural = 'amenities'

    def __str__(self):
        return f"{self.item}"


class BiddingSession(models.Model):
    start_time = models.TimeField()
    end_time = models.TimeField()

    @classmethod
    def current_session_of(cls, property_item):
        """
        Helper function to return current session a property item is in.
        """
        now = timezone.localtime().time()
        qs1 = cls.objects.filter(
            Q(start_time__lte=F('end_time')),
            Q(start_time__lte=now),
            end_time__gte=now,
            propertyitem=property_item)
        qs2 = cls.objects.filter(
            Q(start_time__gt=F('end_time')),
            Q(start_time__lte=now)
            | Q(end_time__gte=now),
            propertyitem=property_item)
        return qs1.union(qs2).first()

    def __str__(self):
        return f"""{self.start_time.strftime('%I:%M %p')} - {self.end_time.strftime('%I:%M %p')}"""


class Sin(models.Func):
    function = 'SIN'


class Cos(models.Func):
    function = 'COS'


class Acos(models.Func):
    function = 'ACOS'


class Radians(models.Func):
    function = 'RADIANS'


class DistanceManager(models.Manager):
    """
    Custom manager that adds functions related to geographical distance.
    """

    def within(self, latitude, longitude):
        """
        Returns the distance between two locations given latitude and
        longitude. The distance is calculated using Haversine Formula. See
        https://en.wikipedia.org/wiki/Haversine_formula
        The model that this manager handles must have a latitude and longitutde
        field.

        Usage:
        >>> class Foo(models.Model):
        >>>     latitude = models.DecimalField()
        >>>     longitude = models.DecimalField()
        >>>     objects = DistanceManager()

        >>> Foo.objects.within(lat, lng)
        <QuerySet [<Foo: ...>]>

        Args:
            latitude: Latitude of the given location
            longitude: Longitude of the given location

        Returns:
            A queryset with annotated distance between the given location and
            objects
        """
        radlat = Radians(latitude)  # given latitude
        radlong = Radians(longitude)  # given longitude
        radflat = Radians(models.F('latitude'))
        radflong = Radians(models.F('longitude'))

        # 6371 is for km. Use 3959 for miles
        expr = 6371 * Acos(
            Cos(radlat) * Cos(radflat) * Cos(radflong - radlong) +
            Sin(radlat) * Sin(radflat))

        return self.get_queryset().annotate(distance=expr)


class Property(models.Model):
    host = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(
        _('title'), max_length=100, help_text=_('Character limit: 100'))
    description = models.TextField(
        _('description'), max_length=600, help_text=_('Character limit: 600'))
    address = models.CharField(
        _('address'), max_length=200, help_text=_('Address of this property.'))
    latitude = models.DecimalField(
        max_digits=10, decimal_places=7, editable=False)
    longitude = models.DecimalField(
        max_digits=10, decimal_places=7, editable=False)
    earliest_checkin_time = models.TimeField(
        _('earliest check-in time'),
        help_text=_('Earliest time a guest can check-in.'))
    latest_checkin_time = models.TimeField(
        _('latest check-in time'),
        help_text=_('Latest time a guest can check-in.'))

    objects = DistanceManager()

    class Meta:
        verbose_name_plural = 'properties'

    def get_absolute_url(self):
        return reverse('core:property-detail', args=[str(self.id)])

    def __str__(self):
        return f"Property: {self.title} owned by {self.host} ({self.longitude}, {self.latitude})"


class PropertyItem(models.Model):
    property = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name='property_item')
    title = models.CharField(
        _('title'), max_length=100, help_text=_('Character limit: 100'))
    description = models.TextField(
        _('description'), max_length=600, help_text=_('Character limit: 600'))
    buyout_price = models.PositiveIntegerField(
        _('buyout price'), help_text=_('Buyout price of the auction.'))
    min_price = models.PositiveIntegerField(
        _('min price'), help_text=_('Starting price of the auction.'))
    session = models.ManyToManyField(
        BiddingSession,
        verbose_name=_('bidding session'),
        blank=True,
        help_text=_('Choose a session to enable bidding during those times.'))
    amenities = models.ManyToManyField(
        Amenity, blank=True, help_text=_('Amenities in this place.'))
    capacity = models.PositiveIntegerField()
    available = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('core:property-detail', args=[str(self.property.id)])

    def __str__(self):
        return f"{self.title}"


def property_item_img_path(instance, filename):
    """
    File will be uploaded to
    MEDIA_ROOT/user_<id>/property_item_<property_item_id>/<filename>
    """
    return f"user_{instance.property_item.property.host.id}/property_item_{instance.property_item.id}/{filename}"


def property_img_path(instance, filename):
    """
    File will be uploaded to
    MEDIA_ROOT/user_<id>/property_<property_item_id>/<filename>
    """
    return f"user_{instance.property.host.id}/property_{instance.property.id}/{filename}"


class PropertyImage(models.Model):
    property = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=property_img_path)


class PropertyItemImage(models.Model):
    property_item = models.ForeignKey(
        PropertyItem, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=property_item_img_path)


class Bid(models.Model):
    property_item = models.ForeignKey(
        PropertyItem, on_delete=models.CASCADE, related_name='bids')
    bidder = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()

    class Meta:
        get_latest_by = 'amount'


class Booking(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    property_item = models.ForeignKey(PropertyItem, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(_('price'))
    earliest_checkin_time = models.DateTimeField(_('earliest check-in time'))
    latest_checkin_time = models.DateTimeField(_('latest check-in time'))

    def __str__(self):
        return f"{self.user} booked {self.property_item}"


class PropertyItemReview(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(6)])
    description = models.TextField(_('description'))


class Notification(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    OUTBID = 'O'
    WON_BID = 'W'
    BUYOUT = 'B'
    MESSAGE_CHOICES = ((OUTBID, 'You have been outbid!'),
                       (WON_BID, 'You have won your auction!'),
                       (BUYOUT,
                        'The item you were bidding on was bought out!'))
    message = models.CharField(
        _('message'),
        max_length=1,
        choices=MESSAGE_CHOICES,
    )
    property_item = models.ForeignKey(PropertyItem, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)


@receiver(m2m_changed, sender=PropertyItem.session.through)
def property_item_m2m_changed(instance, action, pk_set, **kwargs):
    """
    Add/remove cleanup task when session has been added to/removed from the
    property item.
    """
    sessions = BiddingSession.objects.filter(id__in=pk_set)
    if action == 'post_add':
        for i, session in enumerate(sessions):
            schedule, _ = CrontabSchedule.objects.get_or_create(
                minute=session.end_time.minute, hour=session.end_time.hour)
            PeriodicTask.objects.get_or_create(
                crontab=schedule,
                task='localhost.core.tasks.cleanup_bids',
                name=f'PropertyItem-{instance.id} bids cleanup {i}',
                args=json.dumps([instance.id]))
    elif action == 'post_remove':
        names = [
            f'PropertyItem-{instance.id} bids cleanup {i}'
            for session in sessions
        ]
        PeriodicTask.objects.filter(name__in=names).delete()


@receiver(pre_save, sender=PropertyItem)
def property_item_pre_save(instance, **kwargs):
    """
    Enable bids every day at 12nn.
    """
    schedule, _ = CrontabSchedule.objects.get_or_create(hour=12, minute=0)
    try:
        PeriodicTask.objects.get_or_create(
            crontab=schedule,
            task='localhost.core.tasks.enable_bids',
            name=f'Daily bids enable {instance.id}',
            args=json.dumps([instance.id]))
    except IntegrityError:

localhost/dashboard/models.py
from django.db import models

# Create your models here.

localhost/dashboard/forms.py
from datetime import datetime, time, timedelta

from django import forms
from django.contrib.auth import get_user_model
from django.forms.models import ModelForm, inlineformset_factory
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from localhost.core.models import Property, PropertyItem, PropertyItemReview
from localhost.core.utils import parse_address

User = get_user_model()


class DatePicker(forms.DateInput):
    input_type = 'date'


class ProfileForm(ModelForm):
    class Meta:
        model = User
        fields = (
            'bio',
            'dob',
            'gender',
        )
        widgets = {
            'bio': forms.Textarea(attrs={
                'cols': 100,
                'rows': 3
            }),
            'dob': DatePicker(),
            'gender': forms.RadioSelect(),
        }


class PropertyItemForm(ModelForm):
    img = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        label='Photos',
        required=False)

    class Meta:
        model = PropertyItem
        fields = '__all__'
        exclude = ('highest_bidder', )


class PropertyForm(ModelForm):
    # TIME_CHOICE in this format [(time object, time in string)]
    TIME_CHOICE = [((datetime.combine(timezone.now(), time()) +
                     timedelta(minutes=i * 30)).time(),
                    (datetime.combine(timezone.now(), time()) +
                     timedelta(minutes=i * 30)).strftime('%H:%M'))
                   for i in range(48)]
    earliest_checkin_time = forms.ChoiceField(
        choices=TIME_CHOICE, help_text=_('Earliest check-in time.'))
    latest_checkin_time = forms.ChoiceField(
        choices=TIME_CHOICE, help_text=_('Latest check-in time.'))
    img = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        label='Photos',
        required=False)

    class Meta:
        model = Property
        exclude = ('host', )

    def clean(self):
        """
        Clean latest_checkin_time and earliest_checkin_time.

        Ensure that earliest_checkin_time < latest_checkin_time.
        """
        cleaned_data = super().clean()
        earliest_checkin_time = cleaned_data.get('earliest_checkin_time')
        latest_checkin_time = cleaned_data.get('latest_checkin_time')
        if (earliest_checkin_time and latest_checkin_time
                and earliest_checkin_time > latest_checkin_time):
            raise forms.ValidationError(
                _('Invalid check-in time: %(earliest)s > %(latest)s'),
                code='invalid-time',
                params={
                    'earliest': earliest_checkin_time,
                    'latest': latest_checkin_time
                })

    def save(self, commit=True):
        new_property = super().save(commit=False)
        new_property.latitude, new_property.longitude = parse_address(
            self.cleaned_data.get('address'))
        if commit:
            new_property.save()
        return new_property


class WalletForm(forms.Form):
    recharge_amount = forms.IntegerField(
        min_value=1, max_value=9223372036854775807)

    class Meta:
        labels = {
            'recharge_amount': 'Add money to wallet',
        }


class PropertyItemReviewForm(ModelForm):
    class Meta:
        model = PropertyItemReview
        fields = (
            'rating',
            'description',
        )
        labels = {
            'description': 'Leave a review...',
        }
        widgets = {
            'rating': forms.HiddenInput(),
        }


PropertyItemFormSet = inlineformset_factory(
    Property, PropertyItem, form=PropertyItemForm, extra=1)

localhost/dashboard/templates/dashboard/listing/listing_create.html
{% extends "dashboard/listing/listing_form.html" %}

{% block title %} {{ block.super }} - New Listing {% endblock %}

{% block form_title %}New Listing{% endblock %}

localhost/dashboard/templates/dashboard/listing/listing_form.html
{% extends "core/base.html" %}
{% load static %}

{% block css %}

<link rel="stylesheet" type="text/css" href="{% static "core/css/components/header.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/footer.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "core/css/components/panel.css" %}">

{% endblock %}

{% block body_wrapped %}
{% include "core/include/header.html" %}

<div class="container">
  {% block form %}
  <form class="" enctype="multipart/form-data" method="post" novalidate>
    {% csrf_token %}
    <div class="panel">
      <h2>{% block form_title %}Listing{% endblock %} - property details</h2>
      {% include "dashboard/listing/property_form.html" with form=form image_formset=image_formset %}

      {{ property_item_formset.management_form }}
      {% for error in property_item_formset.non_form_errors %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
      {% endfor %}
    </div>

    {% for form in property_item_formset %}
    <div id="property_item-0" class="dynamic-form mt-4 panel">
      <h2>{% block sub_item_title %}New Property Item{% endblock %}</h2>
      {% include 'dashboard/listing/property_item_form.html' with form=form %}
    </div>
    {% endfor %}
    <button type="button" class="btn btn-success btn-raised" onclick="listing_item_clone(); return false;">+ Add Item</button>
    <button type="submit" class="btn btn-primary btn-raised float-right">Create Property</button>
  </form>
  {% endblock %}
</div>

{% include "core/include/footer.html" %}
{% endblock %}

{% block js %}
<script type="text/javascript">
  function update_element_name_id(elem, attr, new_id) {
    var id_str = elem.prop(attr);
    id_str = id_str.replace(/\d+/, new_id);
    elem.prop(attr, id_str);
  }

  function listing_item_clone() {
    /* Calculating the next id */
    var latest_item = $('form .dynamic-form:last');
    var newid = latest_item.attr('id').match(/\d+$/);
    newid++;

    /* Constructing the new item form */
    var new_item = latest_item.clone();
    new_item.children().each(function(i, elem) {
      var tag = $(this).prop('tagName').toLowerCase();
      switch (tag) {
        case 'label':
          update_element_name_id($(this), 'for', newid);
          break;
        case 'input':
        case 'textarea':
          update_element_name_id($(this), 'id', newid);
          update_element_name_id($(this), 'name', newid);
          break;
      }
    });

    new_item.find('.form-group, .form-check').children().each(function() {
      var tag = $(this).prop('tagName').toLowerCase();
      switch (tag) {
        case 'label':
          update_element_name_id($(this), 'for', newid);
          break;
        case 'input':
        case 'textarea':
        case 'select':
          update_element_name_id($(this), 'id', newid);
          update_element_name_id($(this), 'name', newid);
          break;
      }
    });

    $('#id_property_item-TOTAL_FORMS').prop('value', newid+1);

    /* Inserting the new item form into the page */
    update_element_name_id(new_item, 'id', newid);
    new_item.insertAfter(latest_item);
  }
</script>
<script type="text/javascript" src="{% static "core/js/address_search.js" %}"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ GMAPS_KEY }}&libraries=places&callback=activatePlacesSearch"></script>
{% endblock %}

localhost/dashboard/templates/dashboard/listing/property_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {{ error }}
</div>
{% endfor %}
{% endif %}

<div class="form-group">
  <label for="{{ form.title.id_for_label }}" class="sr-only">{{ form.title.label }}</label>
  {% if form.is_bound %}
  {% if form.title.errors %}
  {% render_field form.title class="form-control is-invalid" placeholder=form.title.label %}
  {% for error in form.title.errors %}
  <div class="invalid-feedback">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% else %}
  {% render_field form.title class="form-control is-valid" placeholder=form.title.label %}
  {% endif %}
  {% else %}
  {% render_field form.title class="form-control" placeholder=form.title.label %}
  {% endif %}

  {% if form.title.help_text %}
  <small class="form-text text-muted">{{ form.title.help_text|safe }}</small>
  {% endif %}
</div>
<div class="form-group">
  <label for="{{ form.description.id_for_label }}" class="sr-only">{{ form.description.label }}</label>
  {% if form.is_bound %}
  {% if form.description.errors %}
  {% render_field form.description class="form-control is-invalid" placeholder=form.description.label rows="5" %}
  {% for error in form.description.errors %}
  <div class="invalid-feedback">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% else %}
  {% render_field form.description class="form-control is-valid" placeholder=form.description.label rows="5" %}
  {% endif %}
  {% else %}
  {% render_field form.description class="form-control" placeholder=form.description.label rows="5" %}
  {% endif %}

  {% if form.description.help_text %}
  <small class="form-text text-muted">{{ form.description.help_text|safe }}</small>
  {% endif %}
</div>
{% include "core/include/form_field.html" with form=form field=form.address %}
<div class="form-row">
  {% include "core/include/form_field.html" with form=form field=form.earliest_checkin_time field_extra_css='col-md-6' %}
  {% include "core/include/form_field.html" with form=form field=form.latest_checkin_time field_extra_css='col-md-6' %}
</div>
<div class="form-group">
  {{ form.img.label_tag }}
  {{ form.img }}
  {% if form.img.help_text %}
  <small class="form-text text-muted">{{ form.img.help_text|safe }}</small>
  {% endif %}
</div>

localhost/dashboard/templates/dashboard/listing/property_item_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {{ error }}
</div>
{% endfor %}
{% endif %}

<div class="form-group">
  <label for="{{ form.title.id_for_label }}" class="sr-only">{{ form.title.label }}</label>
  {% if form.is_bound %}
  {% if form.title.errors %}
  {% render_field form.title class="form-control is-invalid" placeholder=form.title.label %}
  {% for error in form.title.errors %}
  <div class="invalid-feedback">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% else %}
  {% render_field form.title class="form-control is-valid" placeholder=form.title.label %}
  {% endif %}
  {% else %}
  {% render_field form.title class="form-control" placeholder=form.title.label %}
  {% endif %}

  {% if form.title.help_text %}
  <small class="form-text text-muted">{{ form.title.help_text|safe }}</small>
  {% endif %}
</div>
<div class="form-group">
  <label for="{{ form.description.id_for_label }}" class="sr-only">{{ form.description.label }}</label>
  {% if form.is_bound %}
  {% if form.description.errors %}
  {% render_field form.description class="form-control is-invalid" placeholder=form.description.label rows="5" %}
  {% for error in form.description.errors %}
  <div class="invalid-feedback">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% else %}
  {% render_field form.description class="form-control is-valid" placeholder=form.description.label rows="5" %}
  {% endif %}
  {% else %}
  {% render_field form.description class="form-control" placeholder=form.description.label rows="5" %}
  {% endif %}

  {% if form.description.help_text %}
  <small class="form-text text-muted">{{ form.description.help_text|safe }}</small>
  {% endif %}
</div>
<div class="form-row">
  {% include "core/include/form_field.html" with form=form field=form.min_price field_extra_css='col-md-4' %}
  {% include "core/include/form_field.html" with form=form field=form.buyout_price field_extra_css='col-md-4' %}
  {% include "core/include/form_field.html" with form=form field=form.capacity field_extra_css='col-md-4' %}
</div>
<div class="form-group">
  {{ form.amenities.label_tag }}
  {% if form.is_bound %}
  {% if form.amenities.errors %}
  {% render_field form.amenities class="form-control is-invalid" %}
  {% for error in form.amenities.errors %}
  <div class="invalid-feedback">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% else %}
  {% render_field form.amenities class="form-control is-valid" %}
  {% endif %}
  {% else %}
  {% render_field form.amenities class="form-control" %}
  {% endif %}

  {% if form.amenities.help_text %}
  <small class="form-text text-muted">{{ form.amenities.help_text|safe }}</small>
  {% endif %}
</div>
<div class="form-group">
  {{ form.session.label_tag }}
  {% if form.is_bound %}
  {% if form.session.errors %}
  {% render_field form.session class="form-control is-invalid" %}
  {% for error in form.session.errors %}
  <div class="invalid-feedback">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% else %}
  {% render_field form.session class="form-control is-valid" %}
  {% endif %}
  {% else %}
  {% render_field form.session class="form-control" %}
  {% endif %}

  {% if form.session.help_text %}
  <small class="form-text text-muted">{{ form.session.help_text|safe }}</small>
  {% endif %}
</div>
<div class="form-group">
  {{ form.img.label_tag }}
  {{ form.img }}
  {% if form.img.help_text %}
  <small class="form-text text-muted">{{ form.img.help_text|safe }}</small>
  {% endif %}
</div>